{% set name = "gemmi" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/project-gemmi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9159506a16e0d22bbeeefc4d34137099318307db1b2bebf06fb2ae501571b19c

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --config-settings="cmake.args=-DBUILD_GEMMI_PROGRAM=ON;-DUSE_ZLIB_NG=ON"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - python
    - pybind11
    - scikit-build-core
    - pip
    - zlib-ng
    - pybind11-stubgen
    - numpy         # [py<=3.10]
    - numpy >=1.26  # [py>3.10]
  run:
    - python

test:
  source_files:
    - tests
    - examples
  commands:
    - gemmi --help
    - pip check
    - python -m unittest discover -s tests -v
  imports:
    - gemmi
  requires:
    - pip
    - numpy

about:
  home: https://project-gemmi.github.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Macromolecular crystallography library and utilities.
  doc_url: https://gemmi.readthedocs.io/
  dev_url: https://github.com/project-gemmi/gemmi

extra:
  recipe-maintainers:
    - ndevenish
    - wojdyr
    - mcs07
