{% set name = "gemmi" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/project-gemmi/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 96e89dcc7e54c7077726dbb6b932a0131b7b5d50b443cc70b24574f747380b2d

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]
    - ninja  # [win]
  host:
    - pybind11
    - python
    - setuptools
    - zlib
  run:
    - python

test:
  commands:
    - gemmi --help
    - python -m gemmi-examples
    - pip check
  imports:
    - gemmi
  requires:
    - pip

about:
  home: https://project-gemmi.github.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Macromolecular crystallography library and utilities.
  doc_url: https://gemmi.readthedocs.io/
  dev_url: https://github.com/project-gemmi/gemmi

extra:
  recipe-maintainers:
    - anthchirp
    - mcs07
